### ISSUE TITLE
paper-icon cannot be shown in ie 11

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#474]
![ss](https://cloud.githubusercontent.com/assets/18186155/17993846/2797590e-6b86-11e6-9ee5-937bb5bde4b8.png)

**Comment by joukevandermaas** [comment]
I cannot reproduce this. Maybe it got fixed in the meantime?

![image](https://cloud.githubusercontent.com/assets/1257578/20965111/9c5b16e2-bc74-11e6-8753-fb7492ff2ca7.png)

**Comment by miguelcobain** [comment]
@joukevandermaas Very likely. Please reopen if issue persists.
