### ISSUE TITLE
paper-slider doesn't work on touch screens

### ISSUE THREAD

**Issue by saerdnaer** [miguelcobain/ember-paper#645]
When I try to move the sliders at http://miguelcobain.github.io/ember-paper/release-1/#/components/slider on in iPad the dot jumps to the left and is not movable anymore. 

![temp](https://cloud.githubusercontent.com/assets/40266/22949780/aba21e00-f303-11e6-9221-fced612227d3.png)

**Comment by miguelcobain** [comment]
@saerdnaer can you please confirm that the fix I pushed to master fixes your problem?

**Comment by saerdnaer** [comment]
@miguelcobain on iOS both with Chrome and Safari the sliders still do not work. Tested also with Chrome on a Galaxy Tab: worked there.

**Comment by miguelcobain** [comment]
@saerdnaer it should **really** be fixed now. ios is tricky.

**Comment by saerdnaer** [comment]
Herby confirmed for the master branch. The demo at http://miguelcobain.github.io/ember-paper/release-1/ might require an redepolyment. ;-)

**Comment by miguelcobain** [comment]
@saerdnaer thanks. i'm seeing something strange in Android. I'm afraid this isn't over yet.

**Comment by miguelcobain** [comment]
Ok, fixed it on android too. Will redeploy demo page soon.
